---
ID: "fafbe16b-6c34-4587-aab2-0117d588c6a0"
Parent: "3d8b8df8-36c4-4060-a391-2e7a92a83bed"
Template: "3d8b8df8-36c4-4060-a391-2e7a92a83bed"
Path: /sitecore/templates/Foundation/ApiGenerator/Settings/Parameter/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171221T021147Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
