---
ID: "2f02c98b-14c1-4121-a308-0da7ad32ddfd"
Parent: "7b041b29-e865-40bd-a30c-021c815407ec"
Template: "a7dc8f8e-f004-46c8-9e31-b2ba852e3df3"
Path: "/sitecore/system/Settings/Foundation/ApiGenerators/Configurations/consumes-types/application x www form urlencoded"
DB: master
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: "application/x-www-form-urlencoded"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180104T152826Z
    - ID: "2c9e1974-f4a6-4dd1-9e7a-d3efa85ae339"
      Hint: Key
      Value: "application/x-www-form-urlencoded"
    - ID: "dd48a3bd-d48d-4109-8519-037a30a52257"
      Hint: Value
      Value: "{2F02C98B-14C1-4121-A308-0DA7AD32DDFD}"
