---
ID: "d89077b3-19db-43f5-a499-295290bff6fb"
Parent: "b6634d58-49d5-435a-ac86-8e47fa7e7939"
Template: "b6634d58-49d5-435a-ac86-8e47fa7e7939"
Path: /sitecore/templates/Foundation/ApiGenerator/Settings/Tag/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180104T191447Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
