---
ID: "8acd6cdd-4a0f-43a0-8d77-4cd815498969"
Parent: "535a7042-c48e-4590-af6c-2b50f687e479"
Template: "1bb0f7c7-8fd0-47d9-9540-c0a9c8bc6dea"
Path: /sitecore/system/Settings/Foundation/ApiGenerators/Blogs/Paths/Articles List/Get/Parameters
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171221T022433Z
